routes/web.php
        Route::post('/reviews/send', 'Site\ReviewsController@send')->name('reviews.send');
        Route::get('/about', 'Site\AboutController')->name('about');
        Route::get('/contacts', 'Site\ContactsController')->name('contacts');
        Route::get('/articles', 'Site\ArticlesController@index')->name('articles');
        Route::get('/articles/{slug}', 'Site\ArticlesController@show')->name('articles.show');

        Route::get('/cart/add', 'Site\CartController@cart_add')->name('products-cart-add');
        Route::get('/cart/del', 'Site\CartController@cart_del')->name('products-cart-del');

        Route::post('/callback', 'Site\CallbackResponseController@sendCallback')->name('callback');
        Route::get('/search', 'Site\SearchController@search')->name('search');
        Route::get('/sitemap.xml', 'Site\SiteMapController@index')->name('sitemap');
        Route::get('/sitemap', 'Site\SiteMapController@page')->name('sitemap.page');

        Route::get('/checkout', 'Site\CheckoutController@cartAction')->name('checkout.cart');
        Route::get('/checkout/info', 'Site\CheckoutController@infoAction')->name('checkout.info');
        Route::get('/checkout/pay', 'Site\CheckoutController@payAction')->name('checkout.pay');
        Route::get('/checkout/success', 'Site\CheckoutController@successAction')->name('checkout.success');

        Route::post('/checkout/submit', 'Site\CheckoutController@submitAction')->name('checkout.submit');
        Route::post('/checkout/promocode', 'Site\CheckoutController@promocodeAction')->name('checkout.promocode');
        Route::post('/checkout/promocode-delete', 'Site\CheckoutController@promocodeDeleteAction')->name('checkout.promocode-delete');

        Route::post('/ajax/buy-one-click', 'Site\BuyOneClickController@popup')->name('ajax.buy-one-click');
        Route::post('/ajax/buy-one-click/submit', 'Site\BuyOneClickController@submit')->name('ajax.buy-one-click.submit');
        Route::post('/ajax/add-to-cart', 'Site\AddToCartController@index')->name('ajax.add-to-cart');

        Route::get('/competition', 'Site\CompetitionController@index')->name('competition');
        Route::post('/competition/submit', 'Site\CompetitionController@submit')->name('competition.submit');
        Route::get('/competition/completed', 'Site\CompetitionController@completed')->name('competition.completed');

        Route::get('/order-status', 'Site\OrderStatusController@index');
        Route::post('/order-status/submit', 'Site\OrderStatusController@submit');

        Route::post('/ajax/competition-rules', 'Site\CompetitionController@rules');
        Route::post('/ajax/bouquet-vote', 'Site\BouquetVoteController@vote');

        Route::post('/ajax/page-info', 'Site\PageInfoController@popup');
        Route::post('/ajax/page-info/submit', 'Site\PageInfoController@submit');

        Route::post('/ajax/filters', 'Site\CatalogController@submitFilters');

        Route::get('/redirect', 'Site\RedirectController@index');
        Route::get('/robots.txt', 'Site\RobotsController@index');

        Route::get('/test', '\App\Console\Commands\TestCommand@test');
    });
});


Route::group(['prefix' => 'admin', 'middleware' => 'auth:admin'], function () {
    Route::name('admin.')->group(function () {
        Route::get('/', 'Admin\MainPageController')->name('main_page');

        Route::resource('franchisee', 'Admin\FranchiseeController');
        Route::resource('delivery', 'Admin\DeliveryController');
        Route::resource('flower', 'Admin\FlowerController');
        Route::resource('promocode', 'Admin\PromocodeController');
        Route::resource('bouquet', 'Admin\BouquetController');
        Route::resource('additional_product', 'Admin\AdditionalProductController', [
            'parameters' => [
                'additional_product' => 'bouquet'
            ]
        ]);
        Route::resource('bouquet_image', 'Admin\BouquetImageController');
        Route::resource('settings/bouquet_reason', 'Admin\BouquetReasonController');
        Route::resource('bouquet_color', 'Admin\BouquetColorController');

        Route::resource('bouquet_category', 'Admin\BouquetCategoryController');
        Route::post('/ajax/bouquet-category-sort', 'Admin\BouquetCategoryController@sort')->name('ajax.bouquet-category-sort');


        Route::get('settings/flower_for_filters', 'Admin\FlowerForFiltersController@index')
            ->name('settings.flower_for_filters.index');
        Route::post('settings/flower_for_filters/change', 'Admin\FlowerForFiltersController@change')
            ->name('settings.flower_for_filters.change');

        Route::resource('settings/banner', 'Admin\BannerController');

        Route::post('bouquet/{bouquet}/update_consist_count', 'Admin\BouquetController@changeConsistCount')
            ->name('bouquet.update_consist_count');
        Route::delete('bouquet/{bouquet}/delete_from_consist', 'Admin\BouquetController@deleteFromConsist')
            ->name('bouquet.delete_flower_from_consist');
        Route::post('bouquet/{bouquet}/add_to_consist', 'Admin\BouquetController@addToConsist')
            ->name('bouquet.add_to_consist');
        Route::post('bouquet/{bouquet}/detach_reason', 'Admin\BouquetController@detachReason')
            ->name('bouquet.detach_reason');
        Route::post('bouquet/{bouquet}/attach_reason', 'Admin\BouquetController@attachReason')
            ->name('bouquet.attach_reason');
        Route::post('bouquet/{bouquet}/detach_color', 'Admin\BouquetController@detachColor')
            ->name('bouquet.detach_color');
        Route::post('bouquet/{bouquet}/attach_category', 'Admin\BouquetController@attachCategory')
            ->name('bouquet.attach_category');

        Route::post('additional_product/{bouquet}/update_consist_count', 'Admin\AdditionalProductController@changeConsistCount')
            ->name('additional_product.update_consist_count');
        Route::delete('additional_product/{bouquet}/delete_from_consist', 'Admin\AdditionalProductController@deleteFromConsist')
            ->name('additional_product.delete_flower_from_consist');
        Route::post('additional_product/{bouquet}/add_to_consist', 'Admin\AdditionalProductController@addToConsist')
            ->name('additional_product.add_to_consist');
        Route::post('additional_product/{bouquet}/detach_reason', 'Admin\AdditionalProductController@detachReason')
            ->name('additional_product.detach_reason');
        Route::post('additional_product/{bouquet}/attach_reason', 'Admin\AdditionalProductController@attachReason')
            ->name('additional_product.attach_reason');
        Route::post('additional_product/{bouquet}/detach_color', 'Admin\AdditionalProductController@detachColor')
            ->name('additional_product.detach_color');
        Route::post('additional_product/{bouquet}/attach_category', 'Admin\AdditionalProductController@attachCategory')
            ->name('additional_product.attach_category');

        Route::get('orders', 'Admin\OrdersController@index')->name('orders.index');
        Route::get('orders/create', 'Admin\OrdersController@create')->name('orders.create');
        Route::post('orders/create', 'Admin\OrdersController@store')->name('orders.store');
        Route::get('orders/edit/{order}', 'Admin\OrdersController@edit')->name('orders.edit');
        Route::put('orders/update/{order}', 'Admin\OrdersController@update')->name('orders.update');
        Route::post('orders/delete/{order}', 'Admin\OrdersController@delete')->name('orders.delete');
        Route::post('orders/calculate', 'Admin\OrdersController@calculate')->name('orders.calculate');

        Route::resource('feedbacks', 'Admin\FeedbacksController');
        Route::resource('articles', 'Admin\ArticlesController');
        Route::resource('settings', 'Admin\SettingsController');
        Route::resource('finance', 'Admin\FinanceController');
    });
});

Route::group(['prefix' => 'admin'], function () {
    Route::name('admin.')->group(function () {
        // Authentication Routes...
        $this->get('login', 'Admin\Auth\LoginController@showLoginForm')->name('login.form');
        $this->post('login', 'Admin\Auth\LoginController@login')->name('login.action');
        $this->post('logout', 'Admin\Auth\LoginController@logout')->name('logout');

        // Password Reset Routes...
        $this->post('password/email', 'Admin\Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
        $this->get('password/reset/{token}', 'Admin\Auth\ResetPasswordController@showResetForm')
            ->name('password.reset');
        $this->post('password/reset', 'Admin\Auth\ResetPasswordController@reset')->name('password.reset.action');
    });
});

Route::group(['prefix' => 'franchisee', 'middleware' => 'auth:franchisee'], function () {
    Route::name('franchisee.')->group(function () {
        Route::get('/', 'Franchisee\MainPageController')->name('main_page');
        Route::resource('orders', 'Franchisee\OrdersController');
        Route::resource('flowers', 'Franchisee\FlowersController');
        Route::resource('products', 'Franchisee\AdditionalProductsController');
        Route::resource('finance', 'Franchisee\FinanceController');
    });
});

Route::group(['prefix' => 'franchisee'], function () {
    Route::name('franchisee.')->group(function () {
        //Auth
        $this->get('login', 'Franchisee\Auth\LoginController@showLoginForm')->name('login.form');
        $this->post('login', 'Franchisee\Auth\LoginController@login')->name('login.action');
        $this->post('logout', 'Franchisee\Auth\LoginController@logout')->name('logout');

        // Password Reset Routes...
        $this->post('password/email', 'Franchisee\Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
        $this->get('password/reset/{token}', 'Franchisee\Auth\ResetPasswordController@showResetForm')
            ->name('password.reset');

app/Http/Controllers/Admin/FinanceController.php
<?php
/**
 * Created by PhpStorm.
 * User: jonic
 * Date: 28.05.2018
 * Time: 11:56
 */

namespace App\Http\Controllers\Admin;


use App\Http\Controllers\Controller;
use App\Models\Franchisee;
use App\Models\FranchiseeLog;
use App\Models\Order;
use Illuminate\Http\Request;

class FinanceController extends Controller
{
    public function index()
    {
        $franchisees = Franchisee::orderBy("city_ru", 'ASC')->paginate(20);
        return view('admin.finance.list', compact('franchisees'));
    }

    public function show(Request $request, $id)
    {
        $franchisee = Franchisee::find($id);
        $today = date("Y-m-d");
        $logs = $franchisee->logs()->where("type", "out")->orderBy("id", "desc")->get();
        return view('admin.finance.show-ajax', compact('franchisee', 'today', 'logs'));
    }

    public function store(Request $request)
    {
        $date = $request->get("date");
        $sum = $request->get("sum");
        $franchise_id = $request->get("franchisee_id");
        $franchisee = Franchisee::find($franchise_id);
        $franchisee->makeLog($date, $sum);
        return ['sucess' => true];
    }

    public function destroy(Request $request, $id)
    {
        $log = FranchiseeLog::find($id);

        //reverse
        $franchisee = $log->franchisee;
        $franchisee->total_payment -= $log->append;
        $franchisee->balance += $log->append;
        $franchisee->save();

        return ['success' => $log->delete()];
    }
}

app/Http/Controllers/Franchisee/FinanceController.php
<?php
/**
 * Created by PhpStorm.
 * User: jonic
 * Date: 28.05.2018
 * Time: 11:56
 */

namespace App\Http\Controllers\Franchisee;


use App\Http\Controllers\Controller;

class FinanceController extends Controller
{
    public function index() {
        $franchisee = auth('franchisee')->user();
        $logs = $franchisee->logs()->where("type","out")->orderBy("id","desc")->paginate(10);
        return view('franchisee.finance.list',compact('franchisee','logs'));
    }
}

resources/views/admin/finance/list.blade.php
@extends('admin.layout.main')

@section('content')
    <div class="row full-width">
        <div class="col-md-8 col-md-offset-2">
            <div class="block">
                <div class="row">
                    <div class="col-sm-12"></div>
                </div>
                <div class="row">
                    <div class="col-md-12 col-sm-12">
                        <div class="table-responsive">
                            <table class="table table-vcenter table-striped">
                                <thead>
                                <tr>
                                    <th>Город</th>
                                    <th>Всего заработано</th>
                                    <th>Всего выведено</th>
                                    <th>Дата последнего вывода денег</th>
                                    <th>Текущий баланс</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($franchisees as $franchisee)
                                    <tr data-open="{{ URL::route('admin.finance.show', $franchisee) }}">
                                        <td>
                                            {{ $franchisee->city_ru }}
                                        </td>
                                        <td>
                                            {{$franchisee->total_cash}}
                                        </td>
                                        <td>
                                            {{$franchisee->total_payment}}
                                        </td>
                                        <td>
                                            {{ $franchisee->total_date ? $franchisee->total_date->format("d.m.Y") : "нет"}}
                                        </td>
                                        <td>
                                            {{ $franchisee->balance }}
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="row justify-content-md-center">
                    <div class="col-md-auto">
                        {{$franchisees->links()}}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="modal" tabindex="-1" role="dialog" id="myModal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" style="text-align: center">Информация/История выводов франчайзи </h4>
                </div>
                <div class="modal-body">
                    <p>text place here</p>
                </div>
                <div class="modal-footer" style="text-align: center">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                </div>
            </div>
        </div>
    </div>
    <style>
        [data-open] {
            transition: all 0.3s;
        }

        [data-open]:hover {
            background:#ff6b6b!important;
            color:#FFF;
            cursor: pointer;
        }

        .rows-scroll {
            height:180px;
            overflow-y: scroll;
            overflow-x: hidden;
            border:1px solid #e8e8e8;
            border-radius: 4px;
            margin-bottom:10px;
            padding:10px;
        }

        .rows-scroll span {
            display:flex;
            align-items: center;
            height:100%;
            justify-content: center;
            color:#EAEAEA;
        }
    </style>
@stop

@push('scripts')
<script>
    function setLoading() {
        $("#myModal .modal-body").html("").addClass("loading");
    }

    function setLoaded() {
        $("#myModal .modal-body").removeClass("loading");
    }

    function loadUrl($url) {
        setLoading();
        $('#myModal').modal('show');
        $.get($url,{},function(response){
            $("#myModal .modal-body").html(response);
            setLoaded();
        });
    }

    var $surl="";

    $(function(){
        $('#myModal').modal({
            show: false
        });
        $("body").on("click","[data-open]",function(e) {
            e.preventDefault();
            $surl = $(this).attr("data-open");
            loadUrl($surl);
            return false;
        });

        $("body").on("click","#myModal button.add",function() {
            var sum = $("#myModal input[type=number]").val();
            var date = $("#myModal input[type=date]").val();
            var id = $(this).attr("data-id");
            $.ajax({
                url: '{{route('admin.finance.store')}}',
                type:'POST',
                data:{
                    sum:sum,
                    date:date,
                    franchisee_id:id
                },
                processData:true,
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
                success:function(e) {
                    loadUrl($surl);
                }
            });
            return false;
        });

        $("body").on("click","#myModal .btn-remove",function() {
            var row = $(this).closest("[data-id]");
            var id = $(row).attr("data-id");
            $.ajax({
                url: '/admin/finance/'+id,
                type:'DELETE',
                data:{
                    franchisee_id:id
                },
                processData:true,
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
                success:function(e) {
                    loadUrl($surl);
                }
            });
            return false;
        });
    });
</script>
@endpush

resources/views/admin/finance/show-ajax.blade.php
<div class="row">
    <div class="col-sm-6">
        <div class="row">
            <div class="col-sm-8">
                <label>Город</label>
            </div>
            <div class="col-sm-4">
                <label>{{$franchisee->city_ru}}</label>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-8">
                <label>Всего заработано</label>
            </div>
            <div class="col-sm-4">
                <label>{{price_format($franchisee->total_cash)}}</label>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-8">
                <label>Всего выведено</label>
            </div>
            <div class="col-sm-4">
                <label>{{price_format($franchisee->total_payment)}}</label>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-8">
                <label>Дата последнего вывода</label>
            </div>
            <div class="col-sm-4">
                <label>{{$franchisee->total_date?$franchisee->total_date->format("d.m.Y"):"нет"}}</label>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-8">
                <label>Текущий баланс</label>
            </div>
            <div class="col-sm-4">
                <label>{{price_format($franchisee->balance)}}</label>
            </div>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="row">
            <div class="col-sm-12">
                <div class="rows-scroll">
                    @if(!sizeof($logs))
                    <span>Выплат не было</span>
                    @endif
                    <table class="table">
                        @foreach($logs as $log)
                        <tr data-id="{{$log->id}}">
                            <td><label>{{$log->created_at->format("d.m.Y")}}</label></td>
                            <td><label>{{price_format($log->append)}}</label> </td>
                            <td width="48"><button class="btn btn-sm btn-link btn-remove"><i class="fa fa-remove"></i></button></td>
                        </tr>
                        @endforeach
                    </table>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="form-group">
                    <input type="date" class="form-control" value="{{$today}}"/>
                </div>
            </div>

        </div>
        <div class="row">
            <div class="col-sm-6">
                <div class="form-group">
                    <input type="number" class="form-control" value="{{$franchisee->balance}}"/>
                </div>
            </div>
            <div class="col-sm-6">
                <button class="btn btn-primary full add" style="width:100%;" data-id="{{$franchisee->id}}"><i class="fa fa-plus"></i> Добавить</button>
            </div>
        </div>
    </div>
</div>