routes/web.php
<?php


//Route::group([
//    'domain' => env('APP_BASE_DOMAIN')
//], function () {
//    Route::name('site.')->group(function () {
//        Route::get('/', 'Site\SelectCityController@index')->name('site.city.display_list');
//    });
//});


//    '{city}.' . env('APP_BASE_MAIN_DOMAIN')

Route::group([
    'middleware' => ['redirect', 'city_of_franchisee'],
], function () {
    Route::name('site.')->group(function () {
        Route::get('/', 'Site\HomePageController')->name('home_page');
        Route::get('/catalog/{slug?}', 'Site\CatalogController')->name('catalog');
        Route::get('/catalog/product/{bouquet}', 'Site\CatalogController@show')->name('catalog.show');
        Route::get('/delivery', 'Site\DeliveryController')->name('delivery');
        Route::get('/reviews/', 'Site\ReviewsController@index')->name('reviews');
        Route::post('/reviews/send', 'Site\ReviewsController@send')->name('reviews.send');
        Route::get('/about', 'Site\AboutController')->name('about');
        Route::get('/contacts', 'Site\ContactsController')->name('contacts');
        Route::get('/articles', 'Site\ArticlesController@index')->name('articles');
        Route::get('/articles/{slug}', 'Site\ArticlesController@show')->name('articles.show');

        Route::get('/cart/add', 'Site\CartController@cart_add')->name('products-cart-add');
        Route::get('/cart/del', 'Site\CartController@cart_del')->name('products-cart-del');

        Route::post('/callback', 'Site\CallbackResponseController@sendCallback')->name('callback');
        Route::get('/search', 'Site\SearchController@search')->name('search');
        Route::get('/sitemap.xml', 'Site\SiteMapController@index')->name('sitemap');
        Route::get('/sitemap', 'Site\SiteMapController@page')->name('sitemap.page');

        Route::get('/checkout', 'Site\CheckoutController@cartAction')->name('checkout.cart');
        Route::get('/checkout/info', 'Site\CheckoutController@infoAction')->name('checkout.info');
        Route::get('/checkout/pay', 'Site\CheckoutController@payAction')->name('checkout.pay');
        Route::get('/checkout/success', 'Site\CheckoutController@successAction')->name('checkout.success');

        Route::post('/checkout/submit', 'Site\CheckoutController@submitAction')->name('checkout.submit');
        Route::post('/checkout/promocode', 'Site\CheckoutController@promocodeAction')->name('checkout.promocode');
        Route::post('/checkout/promocode-delete', 'Site\CheckoutController@promocodeDeleteAction')->name('checkout.promocode-delete');

        Route::post('/ajax/buy-one-click', 'Site\BuyOneClickController@popup')->name('ajax.buy-one-click');
        Route::post('/ajax/buy-one-click/submit', 'Site\BuyOneClickController@submit')->name('ajax.buy-one-click.submit');
        Route::post('/ajax/add-to-cart', 'Site\AddToCartController@index')->name('ajax.add-to-cart');

        Route::get('/competition', 'Site\CompetitionController@index')->name('competition');
        Route::post('/competition/submit', 'Site\CompetitionController@submit')->name('competition.submit');
        Route::get('/competition/completed', 'Site\CompetitionController@completed')->name('competition.completed');

        Route::get('/order-status', 'Site\OrderStatusController@index');
        Route::post('/order-status/submit', 'Site\OrderStatusController@submit');

        Route::post('/ajax/competition-rules', 'Site\CompetitionController@rules');
        Route::post('/ajax/bouquet-vote', 'Site\BouquetVoteController@vote');

        Route::post('/ajax/page-info', 'Site\PageInfoController@popup');
        Route::post('/ajax/page-info/submit', 'Site\PageInfoController@submit');

        Route::post('/ajax/filters', 'Site\CatalogController@submitFilters');

        Route::get('/redirect', 'Site\RedirectController@index');
        Route::get('/robots.txt', 'Site\RobotsController@index');

        Route::get('/test', '\App\Console\Commands\TestCommand@test');
    });
});


Route::group(['prefix' => 'admin', 'middleware' => 'auth:admin'], function () {
    Route::name('admin.')->group(function () {
        Route::get('/', 'Admin\MainPageController')->name('main_page');

        Route::resource('franchisee', 'Admin\FranchiseeController');
        Route::resource('delivery', 'Admin\DeliveryController');
        Route::resource('flower', 'Admin\FlowerController');
        Route::resource('promocode', 'Admin\PromocodeController');
        Route::resource('bouquet', 'Admin\BouquetController');
        Route::resource('additional_product', 'Admin\AdditionalProductController', [
            'parameters' => [
                'additional_product' => 'bouquet'
            ]
        ]);
        Route::resource('bouquet_image', 'Admin\BouquetImageController');
        Route::resource('settings/bouquet_reason', 'Admin\BouquetReasonController');
        Route::resource('bouquet_color', 'Admin\BouquetColorController');

        Route::resource('bouquet_category', 'Admin\BouquetCategoryController');
        Route::post('/ajax/bouquet-category-sort', 'Admin\BouquetCategoryController@sort')->name('ajax.bouquet-category-sort');


        Route::get('settings/flower_for_filters', 'Admin\FlowerForFiltersController@index')
            ->name('settings.flower_for_filters.index');
        Route::post('settings/flower_for_filters/change', 'Admin\FlowerForFiltersController@change')
            ->name('settings.flower_for_filters.change');

        Route::resource('settings/banner', 'Admin\BannerController');

        Route::post('bouquet/{bouquet}/update_consist_count', 'Admin\BouquetController@changeConsistCount')
            ->name('bouquet.update_consist_count');
        Route::delete('bouquet/{bouquet}/delete_from_consist', 'Admin\BouquetController@deleteFromConsist')
            ->name('bouquet.delete_flower_from_consist');
        Route::post('bouquet/{bouquet}/add_to_consist', 'Admin\BouquetController@addToConsist')
            ->name('bouquet.add_to_consist');
        Route::post('bouquet/{bouquet}/detach_reason', 'Admin\BouquetController@detachReason')
            ->name('bouquet.detach_reason');
        Route::post('bouquet/{bouquet}/attach_reason', 'Admin\BouquetController@attachReason')
            ->name('bouquet.attach_reason');
        Route::post('bouquet/{bouquet}/detach_color', 'Admin\BouquetController@detachColor')
            ->name('bouquet.detach_color');
        Route::post('bouquet/{bouquet}/attach_category', 'Admin\BouquetController@attachCategory')
            ->name('bouquet.attach_category');

        Route::post('additional_product/{bouquet}/update_consist_count', 'Admin\AdditionalProductController@changeConsistCount')
            ->name('additional_product.update_consist_count');
        Route::delete('additional_product/{bouquet}/delete_from_consist', 'Admin\AdditionalProductController@deleteFromConsist')
            ->name('additional_product.delete_flower_from_consist');
        Route::post('additional_product/{bouquet}/add_to_consist', 'Admin\AdditionalProductController@addToConsist')
            ->name('additional_product.add_to_consist');
        Route::post('additional_product/{bouquet}/detach_reason', 'Admin\AdditionalProductController@detachReason')
            ->name('additional_product.detach_reason');
        Route::post('additional_product/{bouquet}/attach_reason', 'Admin\AdditionalProductController@attachReason')
            ->name('additional_product.attach_reason');
        Route::post('additional_product/{bouquet}/detach_color', 'Admin\AdditionalProductController@detachColor')
            ->name('additional_product.detach_color');
        Route::post('additional_product/{bouquet}/attach_category', 'Admin\AdditionalProductController@attachCategory')
            ->name('additional_product.attach_category');

        Route::get('orders', 'Admin\OrdersController@index')->name('orders.index');
        Route::get('orders/create', 'Admin\OrdersController@create')->name('orders.create');
        Route::post('orders/create', 'Admin\OrdersController@store')->name('orders.store');
        Route::get('orders/edit/{order}', 'Admin\OrdersController@edit')->name('orders.edit');
        Route::put('orders/update/{order}', 'Admin\OrdersController@update')->name('orders.update');
        Route::post('orders/delete/{order}', 'Admin\OrdersController@delete')->name('orders.delete');
        Route::post('orders/calculate', 'Admin\OrdersController@calculate')->name('orders.calculate');

        Route::resource('feedbacks', 'Admin\FeedbacksController');
        Route::resource('articles', 'Admin\ArticlesController');
        Route::resource('settings', 'Admin\SettingsController');
        Route::resource('finance', 'Admin\FinanceController');
    });
});

Route::group(['prefix' => 'admin'], function () {
    Route::name('admin.')->group(function () {
        // Authentication Routes...
        $this->get('login', 'Admin\Auth\LoginController@showLoginForm')->name('login.form');
        $this->post('login', 'Admin\Auth\LoginController@login')->name('login.action');
        $this->post('logout', 'Admin\Auth\LoginController@logout')->name('logout');

        // Password Reset Routes...
        $this->post('password/email', 'Admin\Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
        $this->get('password/reset/{token}', 'Admin\Auth\ResetPasswordController@showResetForm')
            ->name('password.reset');
        $this->post('password/reset', 'Admin\Auth\ResetPasswordController@reset')->name('password.reset.action');
    });
});

Route::group(['prefix' => 'franchisee', 'middleware' => 'auth:franchisee'], function () {
    Route::name('franchisee.')->group(function () {
        Route::get('/', 'Franchisee\MainPageController')->name('main_page');
        Route::resource('orders', 'Franchisee\OrdersController');
        Route::resource('flowers', 'Franchisee\FlowersController');
        Route::resource('products', 'Franchisee\AdditionalProductsController');

app/Models/Article.php
<?php
/**
 * Created by PhpStorm.
 * User: jonic
 * Date: 29.05.2018
 * Time: 13:33
 */

namespace App\Models;


use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    public $fillable = [
        "slug",
        "title_ru",
        "keywords_ru",
        "description_ru",
        "content_ru",
        "title_en",
        "keywords_en",
        "content_en",
        "description_en",
        "created_at",
        "updated_at",
        'page_title_ru',
        'page_title_en',
        'meta_description_ru',
        'meta_description_en',
    ];

    public function getImageUrlAttribute()
    {
        return \Storage::disk('feedback_images')->url($this->image);
    }


    public static function slugPrepare($title)
    {
        $str = mb_convert_encoding((string)$title, 'UTF-8', mb_list_encodings());

        $char_map = array(
            // Latin
            'À' => 'A', 'Á' => 'A', 'Â' => 'A', 'Ã' => 'A', 'Ä' => 'A', 'Å' => 'A', 'Æ' => 'AE', 'Ç' => 'C',
            'È' => 'E', 'É' => 'E', 'Ê' => 'E', 'Ë' => 'E', 'Ì' => 'I', 'Í' => 'I', 'Î' => 'I', 'Ï' => 'I',
            'Ð' => 'D', 'Ñ' => 'N', 'Ò' => 'O', 'Ó' => 'O', 'Ô' => 'O', 'Õ' => 'O', 'Ö' => 'O', 'Ő' => 'O',
            'Ø' => 'O', 'Ù' => 'U', 'Ú' => 'U', 'Û' => 'U', 'Ü' => 'U', 'Ű' => 'U', 'Ý' => 'Y', 'Þ' => 'TH',
            'ß' => 'ss',
            'à' => 'a', 'á' => 'a', 'â' => 'a', 'ã' => 'a', 'ä' => 'a', 'å' => 'a', 'æ' => 'ae', 'ç' => 'c',
            'è' => 'e', 'é' => 'e', 'ê' => 'e', 'ë' => 'e', 'ì' => 'i', 'í' => 'i', 'î' => 'i', 'ï' => 'i',
            'ð' => 'd', 'ñ' => 'n', 'ò' => 'o', 'ó' => 'o', 'ô' => 'o', 'õ' => 'o', 'ö' => 'o', 'ő' => 'o',
            'ø' => 'o', 'ù' => 'u', 'ú' => 'u', 'û' => 'u', 'ü' => 'u', 'ű' => 'u', 'ý' => 'y', 'þ' => 'th',
            'ÿ' => 'y',
            // Latin symbols
            '©' => '(c)',
            // Greek
            'Α' => 'A', 'Β' => 'B', 'Γ' => 'G', 'Δ' => 'D', 'Ε' => 'E', 'Ζ' => 'Z', 'Η' => 'H', 'Θ' => '8',
            'Ι' => 'I', 'Κ' => 'K', 'Λ' => 'L', 'Μ' => 'M', 'Ν' => 'N', 'Ξ' => '3', 'Ο' => 'O', 'Π' => 'P',
            'Ρ' => 'R', 'Σ' => 'S', 'Τ' => 'T', 'Υ' => 'Y', 'Φ' => 'F', 'Χ' => 'X', 'Ψ' => 'PS', 'Ω' => 'W',
            'Ά' => 'A', 'Έ' => 'E', 'Ί' => 'I', 'Ό' => 'O', 'Ύ' => 'Y', 'Ή' => 'H', 'Ώ' => 'W', 'Ϊ' => 'I',
            'Ϋ' => 'Y',
            'α' => 'a', 'β' => 'b', 'γ' => 'g', 'δ' => 'd', 'ε' => 'e', 'ζ' => 'z', 'η' => 'h', 'θ' => '8',
            'ι' => 'i', 'κ' => 'k', 'λ' => 'l', 'μ' => 'm', 'ν' => 'n', 'ξ' => '3', 'ο' => 'o', 'π' => 'p',
            'ρ' => 'r', 'σ' => 's', 'τ' => 't', 'υ' => 'y', 'φ' => 'f', 'χ' => 'x', 'ψ' => 'ps', 'ω' => 'w',
            'ά' => 'a', 'έ' => 'e', 'ί' => 'i', 'ό' => 'o', 'ύ' => 'y', 'ή' => 'h', 'ώ' => 'w', 'ς' => 's',
            'ϊ' => 'i', 'ΰ' => 'y', 'ϋ' => 'y', 'ΐ' => 'i',
            // Turkish
            'Ş' => 'S', 'İ' => 'I', 'Ç' => 'C', 'Ü' => 'U', 'Ö' => 'O', 'Ğ' => 'G',
            'ş' => 's', 'ı' => 'i', 'ç' => 'c', 'ü' => 'u', 'ö' => 'o', 'ğ' => 'g',
            // Russian
            'А' => 'A', 'Б' => 'B', 'В' => 'V', 'Г' => 'G', 'Д' => 'D', 'Е' => 'E', 'Ё' => 'Yo', 'Ж' => 'Zh',
            'З' => 'Z', 'И' => 'I', 'Й' => 'J', 'К' => 'K', 'Л' => 'L', 'М' => 'M', 'Н' => 'N', 'О' => 'O',
            'П' => 'P', 'Р' => 'R', 'С' => 'S', 'Т' => 'T', 'У' => 'U', 'Ф' => 'F', 'Х' => 'H', 'Ц' => 'C',
            'Ч' => 'Ch', 'Ш' => 'Sh', 'Щ' => 'Sh', 'Ъ' => '', 'Ы' => 'Y', 'Ь' => '', 'Э' => 'E', 'Ю' => 'Yu',
            'Я' => 'Ya',
            'а' => 'a', 'б' => 'b', 'в' => 'v', 'г' => 'g', 'д' => 'd', 'е' => 'e', 'ё' => 'yo', 'ж' => 'zh',
            'з' => 'z', 'и' => 'i', 'й' => 'j', 'к' => 'k', 'л' => 'l', 'м' => 'm', 'н' => 'n', 'о' => 'o',
            'п' => 'p', 'р' => 'r', 'с' => 's', 'т' => 't', 'у' => 'u', 'ф' => 'f', 'х' => 'h', 'ц' => 'c',
            'ч' => 'ch', 'ш' => 'sh', 'щ' => 'sh', 'ъ' => '', 'ы' => 'y', 'ь' => '', 'э' => 'e', 'ю' => 'yu',
            'я' => 'ya',
            // Ukrainian
            'Є' => 'Ye', 'І' => 'I', 'Ї' => 'Yi', 'Ґ' => 'G',
            'є' => 'ye', 'і' => 'i', 'ї' => 'yi', 'ґ' => 'g',
            // Czech
            'Č' => 'C', 'Ď' => 'D', 'Ě' => 'E', 'Ň' => 'N', 'Ř' => 'R', 'Š' => 'S', 'Ť' => 'T', 'Ů' => 'U',
            'Ž' => 'Z',
            'č' => 'c', 'ď' => 'd', 'ě' => 'e', 'ň' => 'n', 'ř' => 'r', 'š' => 's', 'ť' => 't', 'ů' => 'u',
            'ž' => 'z',
            // Polish
            'Ą' => 'A', 'Ć' => 'C', 'Ę' => 'e', 'Ł' => 'L', 'Ń' => 'N', 'Ó' => 'o', 'Ś' => 'S', 'Ź' => 'Z',
            'Ż' => 'Z',
            'ą' => 'a', 'ć' => 'c', 'ę' => 'e', 'ł' => 'l', 'ń' => 'n', 'ó' => 'o', 'ś' => 's', 'ź' => 'z',
            'ż' => 'z',
            // Latvian
            'Ā' => 'A', 'Č' => 'C', 'Ē' => 'E', 'Ģ' => 'G', 'Ī' => 'i', 'Ķ' => 'k', 'Ļ' => 'L', 'Ņ' => 'N',
            'Š' => 'S', 'Ū' => 'u', 'Ž' => 'Z',
            'ā' => 'a', 'č' => 'c', 'ē' => 'e', 'ģ' => 'g', 'ī' => 'i', 'ķ' => 'k', 'ļ' => 'l', 'ņ' => 'n',
            'š' => 's', 'ū' => 'u', 'ž' => 'z'
        );

        $str = str_replace(array_keys($char_map), $char_map, $str);


        // Replace non-alphanumeric characters with our delimiter
        $str = preg_replace('/[^\p{L}\p{Nd}]+/u', "-", $str);

        // Remove duplicate delimiters
        $str = preg_replace('/(' . preg_quote("-", '/') . '){2,}/', '$1', $str);

        // Remove delimiter from ends
        return trim($str, "-");
    }

}

app/Http/Controllers/Admin/ArticlesController.php
<?php
/**
 * Created by PhpStorm.
 * User: jonic
 * Date: 29.05.2018
 * Time: 13:13
 */

namespace App\Http\Controllers\Admin;


use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\Articles\StoreRequest;
use App\Models\Article;
use Request;

class ArticlesController extends Controller
{

    public function index()
    {
        $articles = Article::paginate(10);

        return view('admin.articles.index', compact('articles'));
    }


    public function edit(Article $article)
    {
        return view('admin.articles.edit', compact('article'));
    }


    public function update(StoreRequest $request, Article $article)
    {
        $article->update($request->all());

        return redirect()->route('admin.articles.index');
    }


    public function store(StoreRequest $request)
    {
        $article = Article::create($request->all());

        return redirect()->route('admin.articles.index');
    }


    public function destroy(Article $article)
    {
        try {
            $article->delete();
        } catch (\Exception $exception) {

        }

        return redirect()->route('admin.articles.index');
    }


    public function create()
    {
        return view('admin.articles.add');
    }


    public function show(Article $article)
    {
        //
    }


}

app/Http/Controllers/Site/ArticlesController.php
<?php

namespace App\Http\Controllers\Site;

use App\Models\Article;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

/**
 * Class ArticlesController
 * @package App\Http\Controllers\Site
 */
class ArticlesController extends Controller
{
    public function index()
    {
        $articles = Article::orderBy("id","desc")->get();
        return view('site.articles.index',compact('articles'));
    }

    public function show($city, $slug)
    {
        $article = Article::where("slug",$slug)->first();
        if(!$article) {
            abort(404);
        }
        $articles = Article::where("id","!=",$article->id)->inRandomOrder()->limit(3)->get();
        return view('site.articles.show',compact('article','articles'));
    }
}

resources/views/admin/articles/add.blade.php
@extends('admin.layout.main')

@section('content')
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="block">
                <div class="row">
                    <div class="col-md-12 col-sm-12">
                        {{ Form::open(['route' => 'admin.articles.store', 'method' => 'post', 'class' => 'form-horizontal']) }}


                        <div class="form-group">
                            <label class="col-md-3 control-label" for="example-text-input">Slug<span
                                        class="text-danger">*</span></label>

                            <div class="col-md-9">
                                {{ Form::text('slug', null, ['placeholder' => 'Название (Ru)', 'class' => 'form-control']) }}
                                @if($errors->has('slug'))
                                    <span class="help-block">{{ $errors->first('slug') }}</span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-3 control-label" for="example-text-input">Название (Ru) <span
                                        class="text-danger">*</span></label>
                            <div class="col-md-9">
                                {{ Form::text('title_ru', null, ['placeholder' => 'Название (Ru)', 'class' => 'form-control']) }}
                                @if($errors->has('title_ru'))
                                    <span class="help-block">{{ $errors->first('title_ru') }}</span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-3 control-label" for="example-text-input">Название (En) <span
                                        class="text-danger">*</span></label>
                            <div class="col-md-9">
                                {{ Form::text('title_en', null, ['placeholder' => 'Название (En)', 'class' => 'form-control']) }}
                                @if($errors->has('title_en'))
                                    <span class="help-block">{{ $errors->first('title_en') }}</span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-3 control-label" for="example-text-input">Описание (Ru) <span
                                        class="text-danger">*</span></label>
                            <div class="col-md-9">
                                {{ Form::textarea('content_ru', null, [
                                    'placeholder' => 'Описание (Ru)',
                                    'class' => 'form-control',
                                    'id' => 'article-content-ru'
                                    ]) }}
                                @if($errors->has('content_ru'))
                                    <span class="help-block">{{ $errors->first('content_ru') }}</span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-3 control-label" for="example-text-input">Описание (En) <span
                                        class="text-danger">*</span></label>
                            <div class="col-md-9">
                                {{ Form::textarea('content_en', null, [
                                    'placeholder' => 'Описание (En)',
                                    'class' => 'form-control',
                                    'id' => 'article-content-en'
                                ]) }}
                                @if($errors->has('content_en'))
                                    <span class="help-block">{{ $errors->first('content_en') }}</span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-3 control-label" for="example-text-input">
                                Title (Ru)
                            </label>
                            <div class="col-md-9">
                                {{ Form::text('page_title_ru', null, ['placeholder' => 'Title (Ru)', 'class' => 'form-control']) }}
                                @if($errors->has('page_title_ru'))
                                    <span class="help-block">{{ $errors->first('page_title_ru') }}</span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-3 control-label" for="example-text-input">
                                Title (En)
                            </label>
                            <div class="col-md-9">
                                {{ Form::text('page_title_en', null, ['placeholder' => 'Title (En)', 'class' => 'form-control']) }}

                                @if($errors->has('page_title_en'))
                                    <span class="help-block">{{ $errors->first('page_title_en') }}</span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-3 control-label" for="example-text-input">
                                Meta description (Ru)
                            </label>
                            <div class="col-md-9">
                                {{ Form::textarea('meta_description_ru', null, [
                                    'placeholder' => 'Title (Ru)',
                                    'class' => 'form-control',
                                    'rows' => 2
                                ]) }}

                                @if($errors->has('meta_description_ru'))
                                    <span class="help-block">{{ $errors->first('meta_description_ru') }}</span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-3 control-label" for="example-text-input">
                                Meta description (En)
                            </label>
                            <div class="col-md-9">
                                {{ Form::textarea('meta_description_en', null, [
                                    'placeholder' => 'Title (En)',
                                    'class' => 'form-control',
                                    'rows' => 2
                                ]) }}

                                @if($errors->has('meta_description_en'))
                                    <span class="help-block">{{ $errors->first('meta_description_en') }}</span>
                                @endif
                            </div>
                        </div>


                        <div class="form-group form-actions">
                            <div class="col-md-9 col-md-offset-3">
                                <button type="submit" class="btn btn-sm btn-success"><i class="fa fa-angle-right"></i>
                                    Сохранить
                                </button>
                            </div>
                        </div>

                        {{ Form::close() }}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script type="text/javascript">
        ClassicEditor
                .create(document.querySelector('#article-content-ru'));

        ClassicEditor
                .create(document.querySelector('#article-content-en'));
    </script>
@stop

resources/views/admin/articles/index.blade.php
@extends('admin.layout.main')

@section('content')
    <div class="row full-width">
        <div class="col-md-8 col-md-offset-2">
            <div class="block">
                <div class="row">
                    <div class="col-md-3">
                        <a href="{{ URL::route('admin.articles.create') }}" class="btn btn-success">Добавить <i
                                    class="fa fa-plus"></i></a>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 col-sm-12">
                        <div class="table-responsive">
                            <table class="table table-vcenter table-striped">
                                <thead>
                                <tr>
                                    <th>Наименование</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($articles as $article)
                                    <tr>
                                        <td>
                                            <a href="{{ URL::route('admin.articles.edit', $article) }}">{{ $article->title_ru }}</a>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="row justify-content-md-center">
                    <div class="col-md-auto">
                        {{ $articles->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop